openapi: 3.0.3
info:
  title: Agartex Resource Management Service
  description: |-
    This is a server for making requests to the postgres database instance
  version: 0.0.1
servers:
  - url: http://localhost:3200
tags:
  - name: user
    description: Operations about user
paths:
  /users/{userEmail}:
    parameters:
      - in: path
        name: userEmail
        schema:
          type: string
        required: true
        description: Email of the user to be gotten
    get:
      summary: Get data about user
      tags:
      - user
      description: Returns email and password hash
      responses:
        200:
          description: Data of the user
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/User'
        400:
          description: Malformed request
        404:
          description: User with given email not found
        415:
          description: Wrong content type (should be JSON)
  
  /users:
    post:
      tags: 
        - user
      summary: Create a new user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserData'
      description: Creates a new user using the provided database
      responses:
        201:
          description: User created successfully
        400:
          description: Malformed request
        409:
          description: Could not create user due to conflicts
        415:
          description: Wrong content type (should be JSON)

components:
  schemas:
    UserData:
      type: object
      properties:
        email:
          type: string
          example: john@email.com
        password_hash:
          type: string
          example: idk_even
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        email:
          type: string
          example: john@email.com
        password_hash:
          type: string
          example: idk_even
