openapi: 3.0.3
info:
  title: Agartex Resource Management Service
  description: |-
    This is a server for making requests to the postgres database instance
  version: 0.0.1
servers:
  - url: http://localhost:3200
tags:
  - name: users
    description: CRUD operations for users
  - name: sessions
    description: CRUD operations for sessions
  - name: projects
    description: CRUD operations for projects
  - name: resources
    description: CRUD operations for resources
  - name: documents
    description: CRUD operations for documents
paths:
  /users/{userEmail}:
    parameters:
      - in: path
        name: userEmail
        schema:
          type: string
        required: true
        description: Email of the user to be gotten
    get:
      summary: Get data about user
      tags:
        - users
      description: Returns data of the given user
      responses:
        200:
          description: Data of the user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        400:
          description: Malformed request
        404:
          description: User with given email not found
        422:
          description: Missing paramaters

  /users:
    post:
      tags:
        - users
      summary: Create a new user
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserData"
      description: Creates a new user using the provided database
      responses:
        201:
          description: User created successfully
        400:
          description: Malformed request
        409:
          description: Could not create user due to conflicts
        415:
          description: Wrong content type (should be JSON)
        422:
          description: Missing fields

  /sessions:
    get:
      tags:
        - sessions
      summary: Get data about session
      description: Returns the data of the current session
      security:
        - session_id: []
      responses:
        200:
          description: Data of the session
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Session"
        400:
          description: Malformed request
        404:
          description: Session not found
    delete:
      tags:
        - sessions
      summary: Delete session
      description: Deletes the current session
      security:
        - session_id: []
      responses:
        204:
          description: Successfully deleted session
        400:
          description: Malformed request
    post:
      tags:
        - sessions
      summary: Create a new session
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SessionData"
      description: Creates a new session for the given user
      responses:
        201:
          description: Session created successfully
        400:
          description: Malformed request
        409:
          description: Duplicate session
        415:
          description: Wrong content type (should be JSON)
        422:
          description: Missing fields
  /projects:
    get:
      tags:
        - projects
      summary: Get project list
      description: Returns a list of project for a specific user
      security:
        - user_id: []
      responses:
        200:
          description: Projects list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Project"
        400:
          description: Malformed request
        404:
          description: Project not found

    post:
      tags:
        - projects
      summary: Create a new project
      security:
        - user_id: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProjectMetadata"
      description: Creates a new project
      responses:
        201:
          description: Project created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Project"
        400:
          description: Malformed Request
        415:
          description: Wrong content type (should be JSON)
        422:
          description: Missing fields

  /projects/{projectId}:
    parameters:
      - in: path
        name: projectId
        schema:
          type: integer
        example: 1
        required: true
    get:
      tags:
        - projects
        - documents
      summary: Gets file text
      security:
        - user_id: []
      description: Returns the content of the document associated with the given project
      responses:
        200:
          description: Project text retrieved successfully
          content:
            text/plain:
              schema:
                type: string
        400:
          description: Malformed Request
        404:
          description: Project not found
        422:
          description: Missing paramaters
    put:
      tags:
        - projects
        - documents
      summary: Updates file text
      security:
        - user_id: []
      requestBody:
        content:
          text/plain:
            schema:
              type: string
      description: Updates the content of the document associated with the given project
      responses:
        204:
          description: Project updated successfully
        400:
          description: Malformed Request
        404:
          description: Project not found
        415:
          description: Wrong content type (should be plain text)
        422:
          description: Missing paramaters
  /projects/{projectId}/metadata:
    parameters:
      - in: path
        name: projectId
        schema:
          type: integer
        required: true
    put:
      tags:
        - projects
      summary: Updates metadata of a project
      security:
        - user_id: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProjectMetadata"
      description: Updates the display name of the project
      responses:
        204:
          description: Project updated successfully
        400:
          description: Malformed Request
        404:
          description: Project not found
        415:
          description: Wrong content type (should be JSON)
        422:
          description: Missing paramaters
  /projects/{projectId}/resources:
    parameters:
      - in: path
        name: projectId
        schema:
          type: integer
        required: true
    get:
      tags:
        - resources
        - projects
      summary: Gets metadata of resources in project
      security:
        - user_id: []
      description: Returns a list of metadata of all the resources in the given project
      responses:
        200:
          description: Resource created successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ResourceMetadata"
        400:
          description: Malformed Request
        404:
          description: Project not found
        422:
          description: Missing paramaters
    post:
      tags:
        - resources
        - projects
      summary: Creates new resource in project
      security:
        - user_id: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ResourceMetadata"
      description: Creates a new resource with given name for the given project
      responses:
        201:
          description: Resource created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Resource"
        400:
          description: Malformed Request
        404:
          description: Project not found
        409:
          description: Duplicate resource
        415:
          description: Wrong content type (should be JSON)
        422:
          description: Missing paramaters
  /projects/{projectId}/resources/{resourceId}:
    parameters:
      - in: path
        name: projectId
        schema:
          type: integer
        required: true
      - in: path
        name: resourceId
        schema:
          type: integer
        required: true
    put:
      tags:
        - resources
        - projects
      summary: Updates resource content in project
      security:
        - user_id: []
      requestBody:
        content:
          image/*:
            schema:
              type: string
              format: binary
      description: Uploads new content of a given resource in a given project
      responses:
        204:
          description: Resource uploaded successfully
        400:
          description: Malformed Request
        404:
          description: Project or resource not found
        413:
          description: Uploaded file size larger than allowed
        422:
          description: Missing paramaters

components:
  schemas:
    SessionData:
      type: object
      properties:
        id:
          type: string
        user_id:
          type: integer
        expires:
          type: integer
    Session:
      type: object
      properties:
        id:
          type: string
        user:
          $ref: "#/components/schemas/User"
        expires:
          type: integer

    UserData:
      type: object
      properties:
        email:
          type: string
          example: john@email.com
        password_hash:
          type: string
          example: idk_even
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        email:
          type: string
          example: john@email.com
        password_hash:
          type: string
          example: idk_even
    Project:
      type: object
      properties:
        project_id:
          type: integer
          format: int64
          example: 1
        owner_id:
          type: integer
          format: int64
          example: 1
        owner_email:
          type: string
          format: email
          example: john@email.com
        main_document_id:
          type: integer
          format: int64
          example: 1
        project_name:
          type: string
          example: sample_project
        created_at:
          type: string
          format: timestamp
          example: 2023-06-17 14:23:48.458950
        last_modified:
          type: string
          format: timestamp
          example: 2023-06-17 14:23:48.458950
    ProjectMetadata:
      type: object
      properties:
        name:
          type: string
          example: sample_project
    Resource:
      type: object
      properties:
        resource_id:
          type: string
          example: 1
        project_id:
          type: string
          example: 1
        name:
          type: string
          example: sample_resource.png
    ResourceMetadata:
      type: object
      properties:
        name:
          type: string
          example: sample_resource.png

  securitySchemes:
    user_id:
      type: apiKey
      in: header
      name: X-User-Id
    session_id:
      type: http
      scheme: bearer
      bearerFormat: Session ID
